### ISSUE TITLE
Question: switching windows

### ISSUE THREAD

**Issue by adrian5** [s1n7ax/nvim-window-picker#1]
Just to clarify: this plugin only provides the window ID for further processing, it's not meant to make the selected window the active one, right? I use **hop** extensively and would love to have a window picker to jump between splits without thinking.

**Comment by s1n7ax** [comment]
Yes. This plugin only let you know the window id of the one you selected. In case if you are wondering how to do do it, following will add a `<leader><leader>s` keymap to focus the selected window.

```lua
function focus_window()
    local window = require('window-picker').pick_window()
    vim.api.nvim_set_current_win(window)
end

vim.keymap.set('n', '<leader><leader>s', focus_window)
```
