### ISSUE TITLE
[Feature request] Option to configure selection char placement in statusline

### ISSUE THREAD

**Issue by davidsierradz** [s1n7ax/nvim-window-picker#10]
Hi! Would you consider an option that changes the placement of the selection character in [nvim-window-picker/init.lua at 4df00a6e96b6fe45c7a80bb7d5455c30630b7a55 · s1n7ax/nvim-window-picker](https://github.com/s1n7ax/nvim-window-picker/blob/4df00a6e96b6fe45c7a80bb7d5455c30630b7a55/lua/window-picker/init.lua#L191)? Maybe something like `left|center|right`.

Thanks!

**Comment by thugcee** [comment]
What chances are that this will be merged? I'd love this option.

**Comment by s1n7ax** [comment]
Busy at the moment. I will revisit the requirement soon. The reason this PR was accepted was it only covers the specific 'center' feature and that's all.

**Comment by thugcee** [comment]
For me `All|Center` would be enough. The problem with current `All` behaviour is that it's hard to visually catch selection letters when bars are so wide, bright and there is many of them. But I can use my fork if you don't want this feature. Thank for your time anyway.

**Comment by s1n7ax** [comment]
@davidsierradz @thugcee I have a `release/2.0` branch and there is this breaking change to `selection_display`. Now, the return value from `selection_display` is used as it is. So you have the total control of what you want to do. This branch will eventually merged to main once the testing is completed.

```lua
selection_display = function(char, windowid)
    return [[%#Normal#%=%#IncSearch#     ]] .. char .. [[     %#Normal#%=]]
end,
```

It apparently leaves some area between two windows highlighted by status line highlight. So to remove that use the following in the configuration.

```lua
highlights = {
	statusline = {
		focused = {},
		unfocused = {},
	},
	winbar = {
		focused = {},
		unfocused = {},
	},
}
```

Note that I'm planning to add big letter support in release/2.0 as well. For now you can build a picker like below

```lua
local builder = require('window-picker.builder')
local BigLetterHint = require('window-picker.hints.floating-big-letter-hint')

local windowid = builder
	:new()
	:set_config()
	:set_hint(BigLetterHint:new())
	:set_picker()
	:set_filter()
	:build()
	:pick_window()
```

![image](https://user-images.githubusercontent.com/18459807/220899678-a6796dac-6c3b-4210-83ec-cacc827d03a2.png)
