### ISSUE TITLE
cmdheight=0 doesn't play nice with printed "Pick window"

### ISSUE THREAD

**Issue by yriveiro** [s1n7ax/nvim-window-picker#14]
If the configuration `cmdheight` is configured as `set cmdheight=0` the window highlight for the bottom windows is overridden by the `print('Pick window')`

Nvimtree plugin fixed this by removing the pick window message.

<img width="2201" alt="Screenshot 2022-08-17 at 22 32 54" src="https://user-images.githubusercontent.com/934763/185247167-9058c6a7-b83e-4f60-86f5-9a68945ba0d7.png">

**Comment by dhruvinsh** [comment]
Yes I am in the same boat as you.

**Comment by mehalter** [comment]
@s1n7ax Is there a way to tell `nvim-window-picker` to use `winbar` rather than `statusline` for the selection? I think this would provide a good solution to resolve the issue with `cmdheight=0`

**Comment by s1n7ax** [comment]
https://github.com/s1n7ax/nvim-window-picker/commit/8f5447f2e3a1d2a57cdaabc43be62cec774035ba sets the cmdheight to 1 before showing the picker now. Winbar is also sounds likes a good way.
