### ISSUE TITLE
An option to keep showing window title alongside the shortcut

### ISSUE THREAD

**Issue by strogonoff** [s1n7ax/nvim-window-picker#20]
With `set winminheight=0`, picker shortcut replaces window status meaning it’s impossible to tell which buffer is open in a window if it’s not the maximized one.

**Comment by s1n7ax** [comment]
what?

**Comment by s1n7ax** [comment]
@strogonoff Screenshot?

**Comment by s1n7ax** [comment]
You can use `selection_display` function to fully customize it.
