### ISSUE TITLE
Add option to disable the Pick window prompt

### ISSUE THREAD

**Issue by Nexmean** [s1n7ax/nvim-window-picker#25]
I use winbar for [barbecue](https://github.com/utilyre/barbecue.nvim), and don't want to use it for window indicators. And I don't want to change cmdheight for seeing message `Pick window:`. It would be perfect to have option `use_cmd` set by default to `true`, that can override this behavior.

**Comment by s1n7ax** [comment]
Note that the `use_cmd` was changed to `show_prompt`.
