### ISSUE TITLE
How to make it work when using lazy?

### ISSUE THREAD

**Issue by thepenguinthatwants** [s1n7ax/nvim-window-picker#28]
I tried to install by

```
{
    's1n7ax/nvim-window-picker',
    setup = function()
        require('window-picker').setup()
    end,
},

```
It does install, but when running 

`lua require('nvim-window').pick()`

I get error saiying nvim-window module not found.

**Comment by s1n7ax** [comment]
When you are lazy loading, you need to give tell when to lead the plugin. You could add `even = 'VeryLazy'` for example to load the plugin at startup.
