### ISSUE TITLE
Why assume and only work for upper case selection chars?

### ISSUE THREAD

**Issue by IndianBoy42** [s1n7ax/nvim-window-picker#30]
https://github.com/s1n7ax/nvim-window-picker/blob/65bbc52c27b0cd4b29976fe03be73cc943357528/lua/window-picker/init.lua#L209

Calling upper here means that this doesn't work if I set selection_chars as lowercase. This is a bit weird and also seems completely undocumented. Am I missing something?

**Comment by s1n7ax** [comment]
This is no longer the case in v2
