### ISSUE TITLE
Unable to use in terminal mode.

### ISSUE THREAD

**Issue by mkdir700** [s1n7ax/nvim-window-picker#33]
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/56359329/234214310-286fe9a0-46dd-4947-a976-3d5319f50ea1.png">

When selecting a prompt in terminal mode, the above exception will be thrown.

The exception code is as follows:

https://github.com/s1n7ax/nvim-window-picker/blob/65bbc52c27b0cd4b29976fe03be73cc943357528/lua/window-picker/util.lua#L25

The main reason is that in terminal mode, we don't use `<ESC>` to return to normal mode, but instead use `<C-\\><C-n>`.

**Comment by s1n7ax** [comment]
Apparently this function is no longer in use

**Comment by s1n7ax** [comment]
I don't really understand what "selecting a prompt in terminal mode" means. Could you explain how to recreate?
