### ISSUE TITLE
clear_prompt() break due to key mapping conflic

### ISSUE THREAD

**Issue by NGPONG** [s1n7ax/nvim-window-picker#38]
Hi there, thank for your great work on this plugins.

In my init.lua, I've remapped `:` to other keys, which will cause the following function to not work as expected.

https://github.com/s1n7ax/nvim-window-picker/blob/d3e26ba70dcf3248b2d8a9a9cb6e5ce2e3863bb8/lua/window-picker/util.lua#L37-L39

For more detailed information on this issue please check out nvim-neo-tree/neo-tree.nvim#940

**Comment by s1n7ax** [comment]
This is no longer in use in version 2.
