### ISSUE TITLE
Invalid window id

### ISSUE THREAD

**Issue by yriveiro** [s1n7ax/nvim-window-picker#4]
I hitting this error:

```
E5108: Error executing lua ...im/plugged/nvim-window-picker/lua/window-picker/init.lua:202: Invalid window id: 1015
stack traceback:
        [C]: in function 'nvim_win_set_option'
        ...im/plugged/nvim-window-picker/lua/window-picker/init.lua:202: in function 'pick_window'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

My configuration:

```lua
require 'window-picker'.setup({
	selection_chars = '123345',
})
```

**Comment by s1n7ax** [comment]
Steps to recreate? As far as I can tell, the window should be removed while the window selection. Just wondering how did you manage that?

**Comment by jensenojs** [comment]
<img width="774" alt="image" src="https://github.com/s1n7ax/nvim-window-picker/assets/56761542/bc6bb823-9ad4-41ab-8f10-e29f95c44458">
seems to still happen, using the readme's configuration

**Comment by athanase** [comment]
I currently have the same issue with the configuration provided in the readme.
