### ISSUE TITLE
The `autoselect_one = true` for `s1n7ax/nvim-window-picker` doesn't seem to work with floating Neotree

### ISSUE THREAD

**Issue by nyngwang** [s1n7ax/nvim-window-picker#5]
As title. The picker is still triggered when there is only one window (the floating neo-tree window has been excluded.)

**Comment by s1n7ax** [comment]
I don't understand what you are saying. When where is one two windows, say neo-tree floating window and one other, what do you expect to happen?

**Comment by nyngwang** [comment]
To @s1n7ax:

If you need further explain tag me again.

<img src="https://user-images.githubusercontent.com/24765272/163896934-1e829264-a6d5-4ad1-ab94-5b076d1a1052.png" width="700">

**Comment by s1n7ax** [comment]
INFO: It looks like neo-tree floating window creates two windows. In one of the window buffer `filetype` is just an empty string. That's why window-picker suggest you to select a window.

**Comment by MunifTanjim** [comment]
You can probably also ignore `scratch-buffer` by detecting `buftype=nofile`, because most of the neovim plugins uses `scratch-buffer` for special UIs. Even built-in features like diagnostic popups uses `buftype=nofile`.

**Comment by cseickel** [comment]
I think ignoring floats is a good, universal solution that is probably what most people would want.

**Comment by nyngwang** [comment]
> INFO: It looks like neo-tree floating window creates two windows. In one of the window buffer `filetype` is just an empty string. [...]

@cseickel: I think this is the cause of why `Fzflua files` will fail at the start of neovim: It will not open the selected file but a `[No Name]` buffer because of this, probably.

**Comment by s1n7ax** [comment]
Update to `v1.3` and try. All the floating windows are disabled now.
