### ISSUE TITLE
`focused` and `unfocused` colors are inverted

### ISSUE THREAD

**Issue by loqusion** [s1n7ax/nvim-window-picker#50]
Config:

```lua
{
  highlights = {
    statusline = {
      unfocused = { fg = "#1e1e2e", bg = "#f2cdcd" },
    },
    winbar = {
      unfocused = { fg = "#1e1e2e", bg = "#f2cdcd" },
    },
  },
}
```

![image](https://github.com/s1n7ax/nvim-window-picker/assets/38332081/9cd60401-0597-4f9f-9324-617bb5b62e39)

EDIT: see https://github.com/s1n7ax/nvim-window-picker/issues/50#issuecomment-1650546676

**Comment by zenoli** [comment]
I got the same issue. I could fix it when switching from using lazy.nvim's "opt" table and pass the settings by explictly using require"window-picker".setup in lazy.vim "config" option.

(I did set lazy.nvim's "name" option to "window-picker" so I am confused as to why the "opt" setting is not working.)

**Comment by loqusion** [comment]
Odd, calling `setup` directly doesn't seem to work for me.

**Comment by zenoli** [comment]
Hmm.. I think what I wrote was wrong. I checked again and for me the settings work with the "opt" now as well.
Here is my config in case it helps:

```
return {
    "s1n7ax/nvim-window-picker",
    event = 'VeryLazy',
    version = '2.*',
    opts = {
        -- hint = 'floating-big-letter',
        hint = 'statusline-winbar',
        filter_rules = {
            -- Ignore picker for ft/bt:
            bo = {
                filetype = {
                    "neo-tree",
                    "neo-tree-popup",
                    "notify",
                    "quickfix",
                    "help",
                    "fugitive"
                },
                buftype = { "terminal" },
            },
        },
        highlights = {
            statusline = {
                focused = {
                    fg = '#ededed',
                    bg = '#4493c8',
                    bold = true,
                },
                unfocused = {
                    fg = '#ededed',
                    bg = '#44cc41',
                    bold = true,
                },
            },
        },
    }
}

```

**Comment by loqusion** [comment]
Adding an entry for `highlights.statusline.focused` did it for me. Now, the unfocused windows have the colors specified for `focused`, which shouldn't be the case... right?

**Comment by zenoli** [comment]
Yes I indeed customized to focused values as well.  I never bothered with the concept of "focused/unfocused" but my guess would be that if you have a left and right split, and are currently on the left split while invoking the picker, the left split would be the focused one and the right one the unfocused one. Do you agree and if so, you claim the color settings are inverted?
(I use this plugin merely for picking windows when opening a file from neo-tree, so I all my buffer windows are "unfocussed" according to my guessed definition)

**Comment by loqusion** [comment]
Yeah, it makes more sense for me that the window your cursor is in is "focused" and the others are "unfocused".

Also, my config which only set `unfocused` used to work until a recent change, so maybe there was an introduced bug?

**Comment by zenoli** [comment]
Yes I think this is a bug and our understanding of "focus" is correct. The settings even used to be named `other_win_hl_color` (corresponding to "unfocus") and `current_win_hl_color` (corresponding to "focus") as can be seen in the code (the deprecated settings are still there for backwards compatibility).

I also think the "bug" got somewhat ironically introduced in bugfix #48. Allthough the fix in #48 definitely makes sense, I could not yet see where the error lies. The code looks fine. From what I understand, whatever color is set in the "focus/unfocus" config gets set as value for the "WindowPickerStatusLine"/"WindowPickerStatusLineNC" highlight groups respecitvely, which in turn get linked to the built-in highlight groups "Statusline"/"StatuslineNC" (in the file `statusline-hint.lua`). I don't see where the accidental inversion happens and I don't know why it worked properly prior to #48.

**Comment by loqusion** [comment]
Looking through the code, it seems the highlights and `'winhl'` were being set incorrectly: `StatusLineNC` was being set to `WindowPickerWinBar` in `'winhl'`, and the `WindowPickerWinBar` highlight was being set to `config.highlights.statusline.focused`, so the unfocused windows ended up using the highlights for the focused windows. https://github.com/loqusion/nvim-window-picker/tree/fix/winbar-and-unfocused-highlights fixes the issue for me.

**Comment by zenoli** [comment]
@loqusion nice catch. I was looking at the wrong file (`statusline-hint.lua` instead of `statusline-winbar-hint.lua`).

**Comment by s1n7ax** [comment]
This must be fixed now. Now you can actually use following highlights to set the colors instead of passing them to set up. Though you need to call `setup()` because otherwise it resets back to default colors due to [this](https://github.com/s1n7ax/nvim-window-picker/issues/63) bug
