### ISSUE TITLE
About the api, how to know the user canceled or is there no windows to pick?

### ISSUE THREAD

**Issue by towry** [s1n7ax/nvim-window-picker#51]
It seems both return `nil` value ?

**Comment by s1n7ax** [comment]
Well, you can run the filter manually and see check the count.

```lua
	local Filter = require('window-picker.filters.default-window-filter')
	local filter = Filter:new()
	local all_windows = vim.api.nvim_tabpage_list_wins(0)
	local fwindows = filter:filter_windows(all_windows)
	print(#fwindows)

```

I guess I could throw an error instead. Adding that behavior now is not right. But the entire point of the restructuring of the plugin was to allow extend the behavior of defaults. You can extend the `window-picker/pickers/window-picker.lua` class to throw an error when not window is present and build a new picker. You can upstream so I can add it too
