### ISSUE TITLE
Proposal: rename repository to `window-picker.nvim`

### ISSUE THREAD

**Issue by mehalter** [s1n7ax/nvim-window-picker#58]
Because of the name of the repo being `nvim-window-picker`, in the lazy package manager we need to do `name = "window-picker"` to make it play nicely with the automatic `setup` with the `opts` table. If we rename the repository to `window-picker.nvim` then this would be handled automatically.

Totally understand if you don't want to do this, so feel free to close this! One upside with GitHub is it will automatically forward the original repository name/link to the new location as long as a new repository hasn't been made with the original owner/name

**Comment by s1n7ax** [comment]
At least now, auto config works with lazy nvim so closing this.
