### ISSUE TITLE
configurer.lua:44: attempt to index field 'focused' (a nil value)

### ISSUE THREAD

**Issue by sarmong** [s1n7ax/nvim-window-picker#64]
Bug in the `_backward_compatibility_config_changes` function. `config.highlights.statusline.focused` is nil.

I don't have `highlights` field in my setup and even though `dconfig` creates the full object, [setup function](https://github.com/s1n7ax/nvim-window-picker/blob/1b1bb834b0acb9eebb11a61664efc665757f1ba2/lua/window-picker/init.lua#L89-L92) overwrites it and thus `focused` field is removed.

Not sure how to fix it, therefore creating an issue.

**Comment by lucasrabiec** [comment]
+1

**Comment by XenoPhex** [comment]
The same thing is happening to me, but I'm also running on `HEAD`. So this might also be a bug in Neovim. Might be worth creating an issue in their repo and linking to here.

**Comment by sarmong** [comment]
It has nothing to do with Neovim. Error clearly says that table property is `nil` and I already debugged and described why.

Please, don't clutter their issues.

The solution is just to migrate your window-picker config to the new values (`highlights.statusline`). The problem is only with backwards compatibility.

**Comment by XXiaoA** [comment]
I met the same thing

**Comment by williamboman** [comment]
`git bisect` suggests this might've been a regression introduced in 57cf8cfc4141f693af56f221e97777a889d8aa8a. Using `HEAD` (as of the time of this comment) of neovim. Checking out 6e9875711b9d5cefcf77cc6e30dcce53135b9cc5 seems to fix things for now.
