### ISSUE TITLE
Treesitter-context gets picked up on

### ISSUE THREAD

**Issue by svampkorg** [s1n7ax/nvim-window-picker#67]
When using treesitter-context, the context part gets picked up as possible windows to switch to. Attempting to switch to any of those windows indeed shows there is an ID (thought it changes every time for some reason)

Picking another window from one without any visible treesitter-context:
![no-treesitter-context](https://github.com/s1n7ax/nvim-window-picker/assets/99117038/ed6a335d-714c-4976-a70c-3f87e59a90fa)

Illustration of what I mean with treesitter-context:
![window-with-treesitter-context](https://github.com/s1n7ax/nvim-window-picker/assets/99117038/01525c08-3166-41fb-8a3d-2de3a2d4be61)

Picking another window from a window that had visible treesitter-context:
![trying-to-pick-from-window-with-treesitter-context](https://github.com/s1n7ax/nvim-window-picker/assets/99117038/0fa26529-d3f9-4202-8b8b-66f95e8b6393)

I'm not sure how to filter out those picked up windows :) I've tried with disabling treesitter context, and those rogue window does not show up, so I tried incorporating this in my window picker function, which disables treesitter-context before running window-picker. It looks something like this:

function()
    vim.cmd("TSContextDisable")
    local picked_window_id = require('window-picker').pick_window()
    if vim.fn.win_gettype(picked_window_id) == "unknown" then
        goto enablecontext
    else
        vim.api.nvim_set_current_win(picked_window_id)
        goto enablecontext
    end
    ::enablecontext::
    vim.cmd("TSContextEnable")
end

But this does not work, which is strange because manually disabling treesitter-context before picking a window works.
I think I need some help :)

**Comment by svampkorg** [comment]
for anyone with a similar problem. I kind of solved it after looking a bit at treesitter-context code, by setting this filter rule in window-picker config:
        wo = {
            winhl = { "NormalFloat:TreesitterContext", "NormalFloat:TreesitterContextLineNumber" },
        },

**Comment by 9ary** [comment]
For what it's worth, you were probably running into #66, which is why it wouldn't work.

Here's a filter that works, based on the observation that ts-context makes its windows unfocusable:
```lua
filter_func = function(windows, rules)
	local ret = {}
	for _, wid in ipairs(windows) do
		cfg = vim.api.nvim_win_get_config(wid)
		if not cfg.focusable then
			goto continue
		end
		table.insert(ret, wid)
		::continue::
	end

	local dfilter = require("window-picker.filters.default-window-filter"):new()
	dfilter:set_config(rules)
	return dfilter:filter_windows(ret)
end,
```

This probably ought to be included in the default filter, I'll open a PR for it.

**Comment by okuuva** [comment]
I just ran into this problem and @9ary 's filter_func helped, thanks a lot! Did you end up opening a PR for it? Couldn't find it with a quick search.

**Comment by 9ary** [comment]
> Did you end up opening a PR for it? Couldn't find it with a quick search.

Sorry, never got around to it. I'll try to do that today.

**Comment by 9ary** [comment]
Finally found a moment to prepare a PR, see #90.
