### ISSUE TITLE
How to change the size of floating-big-letter?

### ISSUE THREAD

**Issue by inyutin** [s1n7ax/nvim-window-picker#69]
Hello!

Thank you for your work, that's a wonderful plugin, very useful!
I have only one question: how to change the size of floating-big-letter? Can I make it smaller or maybe I can make it size depend on window size? 

I use this plugin for closing windows without changing focus to them. Usually I need to close LSP references at the bottom. With floating letter it start to look like this:
<img width="1264" alt="image" src="https://github.com/s1n7ax/nvim-window-picker/assets/28871177/1bd8ff6d-4fac-41ee-b182-e0ce5faa74ed">

The letter on the bottom is "D", it got cropped and became unreadable. So with smaller sizes this could be solved

**Comment by s1n7ax** [comment]
It's a floating window. It shouldn't shrink like that.

![image](https://github.com/s1n7ax/nvim-window-picker/assets/18459807/47a9b284-07d6-4ff3-9f82-11b9e2c624d2)

Unfortunately, this is just faking big letters using various characters. So, only way to do this creating a new set of characters that's smaller. I used this application to create letters.

https://patorjk.com/software/taag/
