### ISSUE TITLE
[Feature Request] Autoselect, but only when there's two windows.

### ISSUE THREAD

**Issue by luiz00martins** [s1n7ax/nvim-window-picker#7]
Here's the basic situation:
1. I like the behaviour of `autoselect_one = true` when there's 2 windows (i.e. it automatically goes to the other one), as it takes less keystrokes.
2. I like the behaviour of `include_current_win = true` when there's 3+ windows, as the placement of the selections is a lot more predictable, and I can jump without even looking at the label.

Problem: The two don't work together. With `include_current_win = true`, when there are just 2 windows, `autoselect_one = true` won't trigger, as there are 2 windows to be selected. So I have to disable it to have autoselect, which is unfortunate.

It'd be nice to have a config (or combinations of configs) that would allow `autoselect_one` to trigger when there's 2 windows, but `include_current_win` to work when there's 3+.

_Great plugin btw :)_

**Comment by s1n7ax** [comment]
> I like the behaviour of include_current_win = true when there's 3+ windows, as the placement of the selections is a lot more predictable, and I can jump without even looking at the label.

How is it predictable?

**Comment by prncss-xyz** [comment]
Maybe it could (silently) assign a binding to each window, but display/enact only the ones that pass the filter and include_current_win condition. That way we could also have stability between commands which are using different filters.

**Comment by s1n7ax** [comment]
Try this

```lua
local window_picker = require('window-picker')
local filters = window_picker.filter_windows

local function special_autoselect(windows)
    if #windows > 2 then
        return filters(windows)
    end

    local curr_win = vim.api.nvim_get_current_win()

    for index, window in ipairs(windows) do
        if window == curr_win then
            table.remove(windows, index)
        end
    end

    return filters(windows)
end

window_picker.setup({
    autoselect_one = true,
    include_current_win = true,

    filter_func = special_autoselect,

    filter_rules = {
        bo = {
            filetype = { 'NvimTree', 'neo-tree', 'notify' },
        },
    },
})
```

**Comment by luiz00martins** [comment]
That's... perfect! Configurability >> Configurations

Thanks a lot!
