### ISSUE TITLE
Doesn't play well with lazyvim plugins

### ISSUE THREAD

**Issue by nadeemkhedr** [s1n7ax/nvim-window-picker#84]
I created an issue in lazyvim https://github.com/LazyVim/LazyVim/issues/3795

But found the issue wasn't related to lazyvim, the issue is one of the plugins in lazyvim dosen't play well with window-picker (most likely noice), Not sure which one

When adding a change and doing an undo will show a message on the bottom right, when that message is shown and trying to select a window using `neo-tree` getting, details are in the other issue created in LazyVim

![2024-06-24_13-58-33](https://github.com/s1n7ax/nvim-window-picker/assets/180256/e313cf6d-3dbc-438c-b7cd-b498af5304a7)

I am sure this can be configured, not sure how tbh

**Comment by nadeemkhedr** [comment]
issue was with `noice` adding `noice` to the excluded file types fixed the issue for me

```lua
return {
  "s1n7ax/nvim-window-picker",
  name = "window-picker",
  event = "VeryLazy",
  version = "2.*",
  config = function()
    require("window-picker").setup({
      selection_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
      filter_rules = {
        include_current_win = false,
        autoselect_one = true,
        -- filter using buffer options
        bo = {
          -- if the file type is one of following, the window will be ignored
          filetype = { "neo-tree", "neo-tree-popup", "notify", "noice" },
          -- if the buffer type is one of following, the window will be ignored
          buftype = { "terminal", "quickfix" },
        },
      },
    })
  end,
}
```

**Comment by i11010520** [comment]
> issue was with `noice` adding `noice` to the excluded file types fixed the issue for me
> 
> ```lua
> return {
>   "s1n7ax/nvim-window-picker",
>   name = "window-picker",
>   event = "VeryLazy",
>   version = "2.*",
>   config = function()
>     require("window-picker").setup({
>       selection_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
>       filter_rules = {
>         include_current_win = false,
>         autoselect_one = true,
>         -- filter using buffer options
>         bo = {
>           -- if the file type is one of following, the window will be ignored
>           filetype = { "neo-tree", "neo-tree-popup", "notify", "noice" },
>           -- if the buffer type is one of following, the window will be ignored
>           buftype = { "terminal", "quickfix" },
>         },
>       },
>     })
>   end,
> }
> ```

I copied this config into `.config/lua/plugin/`, after reloading `nvim` and press `w` above some file in the left `neo-tree` view, the window identifier letter cannot appear.

**Comment by i11010520** [comment]
> > issue was with `noice` adding `noice` to the excluded file types fixed the issue for me
> > ```lua
> > return {
> >   "s1n7ax/nvim-window-picker",
> >   name = "window-picker",
> >   event = "VeryLazy",
> >   version = "2.*",
> >   config = function()
> >     require("window-picker").setup({
> >       selection_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
> >       filter_rules = {
> >         include_current_win = false,
> >         autoselect_one = true,
> >         -- filter using buffer options
> >         bo = {
> >           -- if the file type is one of following, the window will be ignored
> >           filetype = { "neo-tree", "neo-tree-popup", "notify", "noice" },
> >           -- if the buffer type is one of following, the window will be ignored
> >           buftype = { "terminal", "quickfix" },
> >         },
> >       },
> >     })
> >   end,
> > }
> > ```
> 
> I copied this config into `.config/lua/plugin/`, after reloading `nvim` and press `w` above some file in the left `neo-tree` view, the window identifier letter cannot appear.

I figure out.
Inserting a line of  `hint = 'floating-big-letter' into the `setup()` block will make it work.
