### ISSUE TITLE
Doesn't work well with "b0o/incline.nvim" floating statusline.

### ISSUE THREAD

**Issue by oneeyedreaper** [s1n7ax/nvim-window-picker#86]
Greetings,
My Apologies if the issue description is not apt since this is my first time writing one.

**The Problem**
It seems like the plugin also considers the incline floating winbar as a window(which in hindsight is valid since it technically is a window), I'd like it to not do so since with multiple splits it becomes hard to navigate. Is there a workaround or fix for this?
[Video](https://drive.google.com/file/d/1SOrY84c0MCuL0RO473fEZ6Po565mG29l/view?usp=sharing) for demo.

Thank You.

**Comment by okuuva** [comment]
@oneeyedreaper have you checked if the filter function for ignoring unfocuseable given in [#67 (comment)](https://github.com/s1n7ax/nvim-window-picker/issues/67#issuecomment-2017825156) work for this use case?

**Comment by okuuva** [comment]
I tested `incline.nvim` myself since I already have the unfocuseable filter in place. Seems to do the trick, floating winbars aren't suggested when picking a window.

**Comment by oneeyedreaper** [comment]
Thank you for the response. This worked like a charm. Closing the issue.
